<h1><b>Linear Algebra for Cpe<b>

<h4><b>Laboratory 6 : Matrices<b>
    

<h5><i>Coded and Submitted by:<i>
<h5><i>Alvarez, Lee Andrei D.<i>
<h5><i>58011<i>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

<h5>Task 1<i>

In [189]:
## Function Area 
def mat_desc(matrix): 
  square = True if matrix.shape[0] == matrix.shape[1] else False 
  empty = matrix.size == 0
  zero_mat_sqr = np.zeros((4,4))
  ones_mat_sqr = np.ones((4,4))
  identity = np.eye(4)
  print(f'Matrix:\n{matrix}','\n'f'Shape:\t{matrix.shape}','\n',f'Size:\t{matrix.size}','\n',f'Rank:\t{matrix.ndim}',
        '\n',f'Square: {square}','\n',f'Empty: {empty}','\n',f'Identity Matrix:\n {identity}','\n',
        f'Ones Matrix:\n {ones_mat_sqr}','\n',f'Zeros Matrix:\n {zero_mat_sqr}')

In [190]:
## Matrix Declarations
A = np.array([[3, -2, 1, 4],[5, -4, 3, 2],[4, 2, -1, -4],[6, 2, -4, -3]])
B = np.array([[6, 3, -1, 2],[2, 4, -3, 2],[3, -2, 1, -4],[7, 2, -6, 3]])
C = np.array([[1, -3, 6, 8],[6, -5, 8, 3],[1, 7, -3, -9],[10, 3, -4, -7]])
D = np.array([[2, -4, 6, 8],[10, -12, 14, 16],[3, 6, -9, -12],[4, 8, -12, -16]])
E = np.array([[1, -3, 5, 7],[9, -12, 15, 17],[5, 10, -15, -20],[6, 12, -18, -24]])

In [191]:
## Test Area 
mat_desc(A)
print('\t')
mat_desc(B)
print('\t')
mat_desc(C)
print('\t')
mat_desc(D)
print('\t')
mat_desc(E)

Matrix:
[[ 3 -2  1  4]
 [ 5 -4  3  2]
 [ 4  2 -1 -4]
 [ 6  2 -4 -3]] 
Shape:	(4, 4) 
 Size:	16 
 Rank:	2 
 Square: True 
 Empty: False 
 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
 Ones Matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
	
Matrix:
[[ 6  3 -1  2]
 [ 2  4 -3  2]
 [ 3 -2  1 -4]
 [ 7  2 -6  3]] 
Shape:	(4, 4) 
 Size:	16 
 Rank:	2 
 Square: True 
 Empty: False 
 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
 Ones Matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
	
Matrix:
[[ 1 -3  6  8]
 [ 6 -5  8  3]
 [ 1  7 -3 -9]
 [10  3 -4 -7]] 
Shape:	(4, 4) 
 Size:	16 
 Rank:	2 
 Square: True 
 Empty: False 
 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
 Ones Matrix:
 [[1. 1. 1. 1.]
 [1. 1.

<h5>Task 2<i>

In [192]:
## Function Area 
def isScalarMatrix(mat) : 
    for x in range(0,len(mat[0])) : 
        for y in range(0,len(mat[0])) : 
            if ((x != y) 
            and (mat[x][y] != 0)) : 
                return False
    for x in range(0,len(mat[0])-1) : 
        if (mat[x][x] !=
        mat[x + 1][x + 1]) : 
            return False
    return True
 
def mat_operations(matrix1, matrix2):
    try:
      name = ""
      if(isScalarMatrix(matrix1) and isScalarMatrix(matrix2)):
          name = "Scalar"
      else:
          name = "Matrix"
      sum = matrix1 + matrix2
      difference = matrix1 - matrix2
      product = np.multiply(matrix1,matrix2)
      quotient = np.divide(matrix1,matrix2)
      print(f'Sum of {name}:\n{sum}','\n',f'Difference of {name}:\n{difference}','\n',f'Product of {name}:\n{product}','\n'f'Product of {name}:\n{product}')
    except:
      print("Matrices are not viable for operations")

In [193]:
## Matrix Declartion
a = np.array([[3, -2, 1, 4],[5, -4, 3, 2],[4, 2, -1, -4],[6, 2, -4, -3]])
b = np.array([[6, 3, -1, 2],[2, 4, -3, 2],[3, -2, 1, -4],[7, 2, -6, 3]])
c = np.array([[1, -3, 6, 8],[6, -5, 8, 3],[1, 7, -3, -9],[10, 3, -4, -7]])
d = np.array([[2, -4, 6, 8],[10, -12, 14, 16],[3, 6, -9, -12],[4, 8, -12, -16]])
e = np.array([[1, -3, 5, 7],[9, -12, 15, 17],[5, 10, -15, -20],[6, 12, -18, -24]])

In [194]:
## Test Area 
mat_operations(a,e)

Sum of Matrix:
[[  4  -5   6  11]
 [ 14 -16  18  19]
 [  9  12 -16 -24]
 [ 12  14 -22 -27]] 
 Difference of Matrix:
[[  2   1  -4  -3]
 [ -4   8 -12 -15]
 [ -1  -8  14  16]
 [  0 -10  14  21]] 
 Product of Matrix:
[[ 3  6  5 28]
 [45 48 45 34]
 [20 20 15 80]
 [36 24 72 72]] 
Product of Matrix:
[[ 3  6  5 28]
 [45 48 45 34]
 [20 20 15 80]
 [36 24 72 72]]
